services:
  db:
    build:
      context: ./db
    environment:
      POSTGRES_DB: stayconnected
      POSTGRES_USER: stayconnected
      POSTGRES_PASSWORD: localdev
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
