"""presence followup and bio matching fields

Revision ID: 14862f714faf
Revises: e7c2085d3fb1
Create Date: 2026-08-31 09:54:38.683046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# `location` (PostGIS Geography, NOT NULL) and `bio_embedding` (pgvector) below
# are pre-Orbit and dropped by the prune migration, so they are now plain
# nullable Text/JSON: history builds without either extension. Originals in git.


# revision identifiers, used by Alembic.
revision: str = '14862f714faf'
down_revision: Union[str, None] = 'e7c2085d3fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follow_ups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stamp_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stamp_id'], ['stamps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('bio_text', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('intent_tags', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('bio_embedding', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio_embedding')
    op.drop_column('users', 'intent_tags')
    op.drop_column('users', 'bio_text')
    op.drop_table('follow_ups')
    op.drop_table('presence')
    # ### end Alembic commands ###
