"""presence followup and bio matching fields

Revision ID: 14862f714faf
Revises: e7c2085d3fb1
Create Date: 2026-08-31 09:54:38.683046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.alembic_types import embedding_column, location_column


# revision identifiers, used by Alembic.
revision: str = '14862f714faf'
down_revision: Union[str, None] = 'e7c2085d3fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # vector/postgis are created in env.py when the instance allows them.
    op.create_table('presence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    location_column(nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: geoalchemy2 automatically creates the GIST spatial index for the
    # 'location' column via an after_create DDL event when the table is
    # created, so no explicit op.create_index call is needed (or wanted) here.
    op.create_table('follow_ups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stamp_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stamp_id'], ['stamps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('bio_text', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('intent_tags', sa.JSON(), nullable=True))
    op.add_column('users', embedding_column())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio_embedding')
    op.drop_column('users', 'intent_tags')
    op.drop_column('users', 'bio_text')
    op.drop_table('follow_ups')
    op.drop_table('presence')
    # ### end Alembic commands ###
